export const cars = [
  {
    id: '1',
    name: 'BMW 740Li M Sport',
    nameAr: 'بي ام دبليو 740Ci ام سبورت',
    brand: 'BMW',
    brandAr: 'بي ام دبليو',
    type: 'sedan',
    typeAr: 'سيدان',
    year: 2024,
    mileage: 12500,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أبيض كيراميك',
    colorEn: 'Ceramic White',
    location: 'الرياض',
    locationEn: 'Riyadh',
    price: 385000,
    startingBid: null,
    image: '/assets/cars/sedan_luxury.jpg',
    badge: null,
    engine: '3.0L Inline-6 Turbo',
    power: '380 hp',
    torque: '520 Nm',
    drivetrain: 'RWD',
    acceleration: '5.4s',
    fuelEconomy: '8.2 L/100km',
    dimensions: '5391 × 1902 × 1540 mm',
    weight: '2015 kg',
    interior: 'فاخر - جلد داكن',
    wheels: '20" M Sport',
    climate: 'تكييف ثنائي المنطقة',
    seller: { name: 'أحمد العلي', rating: 4.8, reviews: 124 },
    features: ['كاميرا 360°', 'نظام ملاحة', 'مقاعد مساج', 'سقف بانورامي', '揄uma مزدوجة'],
    isAuction: false,
  },
  {
    id: '2',
    name: 'Mercedes S500 AMG Line',
    nameAr: 'مرسيدس S500 ام بي جي لاين',
    brand: 'Mercedes',
    brandAr: 'مرسيدس',
    type: 'sedan',
    typeAr: 'سيدان',
    year: 2024,
    mileage: 8900,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أسود أونيكس',
    colorEn: 'Onyx Black',
    location: 'جدة',
    locationEn: 'Jeddah',
    price: 420000,
    startingBid: null,
    image: '/assets/cars/sedan_luxury.jpg',
    badge: null,
    engine: '3.0L Inline-6 Turbo',
    power: '449 hp',
    torque: '560 Nm',
    drivetrain: 'AWD',
    acceleration: '4.9s',
    fuelEconomy: '9.1 L/100km',
    dimensions: '5469 × 1921 × 1510 mm',
    weight: '2135 kg',
    interior: 'فاخر - جلد نابا',
    wheels: '21" AMG Multi-spoke',
    climate: 'تكييف ثلاثي المناطق',
    seller: { name: 'خالد المطيري', rating: 4.9, reviews: 89 },
    features: ['شاشتان أماميتان', 'نظام صوت Burmester', 'إضاءة محيطية', '開門 كهربائي'],
    isAuction: false,
  },
  {
    id: '3',
    name: 'Toyota Land Cruiser VX',
    nameAr: 'تويوتا لاند كروزر VX',
    brand: 'Toyota',
    brandAr: 'تويوتا',
    type: 'suv',
    typeAr: 'دفع رباعي',
    year: 2025,
    mileage: 1200,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'فضي ميتاليك',
    colorEn: 'Silver Metallic',
    location: 'الدمام',
    locationEn: 'Dammam',
    price: 265000,
    startingBid: 180000,
    image: '/assets/cars/suv_land_cruiser.jpg',
    badge: null,
    engine: '3.5L V6 Twin-Turbo',
    power: '409 hp',
    torque: '650 Nm',
    drivetrain: 'AWD',
    acceleration: '6.7s',
    fuelEconomy: '11.4 L/100km',
    dimensions: '4985 × 1980 × 1935 mm',
    weight: '2600 kg',
    interior: 'فاخر - جلد بني',
    wheels: '20" ألومنيوم',
    climate: 'تكييف ثلاثي المناطق',
    seller: { name: 'فهد الشمري', rating: 4.7, reviews: 203 },
    features: [' نظام كينetic Suspension', 'كاميرا أمامية', 'نظام هيدروليك', 'فتحة سقف'],
    isAuction: true,
    currentBid: 195000,
    bidCount: 24,
    lastBidTime: '2 دقيقة',
    endsAt: Date.now() + 3 * 60 * 60 * 1000 + 17 * 60 * 1000 + 42 * 1000,
  },
  {
    id: '4',
    name: 'BMW X7 M60i',
    nameAr: 'بي ام دبليو X7 M60i',
    brand: 'BMW',
    brandAr: 'بي ام دبليو',
    type: 'suv',
    typeAr: 'دفع رباعي',
    year: 2024,
    mileage: 15000,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أزرق ميتاليك',
    colorEn: 'Blue Metallic',
    location: 'الرياض',
    locationEn: 'Riyadh',
    price: 495000,
    startingBid: null,
    image: '/assets/cars/suv_g_class.jpg',
    badge: null,
    engine: '4.4L V8 Twin-Turbo',
    power: '530 hp',
    torque: '750 Nm',
    drivetrain: 'AWD',
    acceleration: '4.7s',
    fuelEconomy: '12.8 L/100km',
    dimensions: '5181 × 2000 × 1835 mm',
    weight: '2680 kg',
    interior: 'فاخر - جلد Cashmere',
    wheels: '22" M Sport',
    climate: 'تكييف رباعي المناطق',
    seller: { name: 'محمد العتيبي', rating: 4.6, reviews: 67 },
    features: ['شاشة 12.3"', 'نظام صوت Harman Kardon', 'مقاعد مبردة', 'باب خلفية كهربائية'],
    isAuction: false,
  },
  {
    id: '5',
    name: 'Mercedes G63 AMG',
    nameAr: 'مرسيدس G63 ام بي جي',
    brand: 'Mercedes',
    brandAr: 'مرسيدس',
    type: 'suv',
    typeAr: 'دفع رباعي',
    year: 2024,
    mileage: 22000,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'رمادي مات',
    colorEn: 'Matte Grey',
    location: 'جدة',
    locationEn: 'Jeddah',
    price: 680000,
    startingBid: 520000,
    image: '/assets/cars/suv_g_class.jpg',
    badge: '🔥 Most in Demand',
    engine: '4.0L V8 Biturbo',
    power: '585 hp',
    torque: '850 Nm',
    drivetrain: 'AWD',
    acceleration: '4.5s',
    fuelEconomy: '14.2 L/100km',
    dimensions: '4873 × 1984 × 1969 mm',
    weight: '2560 kg',
    interior: 'فاخر - جلد Designo',
    wheels: '22" AMG Cross-spoke',
    climate: 'تكييف ثنائي المناطق',
    seller: { name: 'سعد القحطاني', rating: 5.0, reviews: 31 },
    features: ['نظام AMG Ride Control', 'إطار احتياطي خارجي', 'نظام صوت Burmester 3D', 'مقاعد رياضية'],
    isAuction: true,
    currentBid: 545000,
    bidCount: 47,
    lastBidTime: '30 ثانية',
    endsAt: Date.now() + 0 * 60 * 60 * 1000 + 3 * 60 * 1000 + 15 * 1000,
  },
  {
    id: '6',
    name: 'Nissan Patrol Platinum',
    nameAr: 'نيسان باترول بلاتينيوم',
    brand: 'Nissan',
    brandAr: 'نيسان',
    type: 'suv',
    typeAr: 'دفع رباعي',
    year: 2025,
    mileage: 500,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أبيض لؤلؤي',
    colorEn: 'Pearl White',
    location: 'الرياض',
    locationEn: 'Riyadh',
    price: 245000,
    startingBid: null,
    image: '/assets/cars/suv_land_cruiser.jpg',
    badge: null,
    engine: '5.6L V8',
    power: '400 hp',
    torque: '560 Nm',
    drivetrain: 'AWD',
    acceleration: '6.5s',
    fuelEconomy: '13.5 L/100km',
    dimensions: '5175 × 1995 × 1940 mm',
    weight: '2780 kg',
    interior: 'فاخر - جلد بيج',
    wheels: '22" ألمنيوم',
    climate: 'تكييف ثلاثي المناطق',
    seller: { name: 'عبدالله السبيعي', rating: 4.5, reviews: 156 },
    features: ['شاشة 12.3"', 'نظام ProPILOT', 'مقاعد مساج', 'باب خلفية كهربائية'],
    isAuction: false,
  },
  {
    id: '7',
    name: 'Ford F-150 Raptor',
    nameAr: 'فورد F-150 رابتور',
    brand: 'Ford',
    brandAr: 'فورد',
    type: 'pickup',
    typeAr: 'بيك أب',
    year: 2024,
    mileage: 32000,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'برتقالي آسيوي',
    colorEn: 'Velocity Blue',
    location: 'الدمام',
    locationEn: 'Dammam',
    price: 310000,
    startingBid: null,
    image: '/assets/cars/pickup_f150.jpg',
    badge: null,
    engine: '3.5L V6 EcoBoost',
    power: '450 hp',
    torque: '691 Nm',
    drivetrain: 'AWD',
    acceleration: '5.2s',
    fuelEconomy: '12.4 L/100km',
    dimensions: '5890 × 2030 × 1960 mm',
    weight: '2680 kg',
    interior: 'رياضي - جلد أسود',
    wheels: '17" Beadlock-capable',
    climate: 'تكييف ثنائي المناطق',
    seller: { name: 'يوسف الحربي', rating: 4.4, reviews: 78 },
    features: ['نظام Fox Racing Shox', 'Control Trac 4WD', 'SYNC 4', 'مقاعد مدفأة'],
    isAuction: false,
  },
  {
    id: '8',
    name: 'GMC Yukon Denali',
    nameAr: 'جي إم سي يوكون دينالي',
    brand: 'GMC',
    brandAr: 'جي إم سي',
    type: 'suv',
    typeAr: 'دفع رباعي',
    year: 2024,
    mileage: 18000,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أسود أونيكس',
    colorEn: 'Onyx Black',
    location: 'جدة',
    locationEn: 'Jeddah',
    price: 375000,
    startingBid: null,
    image: '/assets/cars/suv_g_class.jpg',
    badge: null,
    engine: '6.2L V8',
    power: '420 hp',
    torque: '624 Nm',
    drivetrain: 'AWD',
    acceleration: '6.1s',
    fuelEconomy: '14.7 L/100km',
    dimensions: '5357 × 2057 × 1943 mm',
    weight: '2700 kg',
    interior: 'فاخر - جلد عسلي',
    wheels: '22" مطاوية',
    climate: 'تكييف ثلاثي المناطق',
    seller: { name: 'راشد العنزي', rating: 4.3, reviews: 92 },
    features: ['Magnetic Ride Control', 'Head-Up Display', 'نظام صوت Bose', 'فتحة سقف كهربائية'],
    isAuction: false,
  },
  {
    id: '9',
    name: 'Toyota GR Supra',
    nameAr: 'تويوتا GR سوبرا',
    brand: 'Toyota',
    brandAr: 'تويوتا',
    type: 'sports',
    typeAr: 'رياضية',
    year: 2024,
    mileage: 8500,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أحمر وردي',
    colorEn: 'Red Solid',
    location: 'الرياض',
    locationEn: 'Riyadh',
    price: 195000,
    startingBid: 150000,
    image: '/assets/cars/sports_orange.jpg',
    badge: '⚡ Ending Soon',
    engine: '3.0L Inline-6 Turbo',
    power: '382 hp',
    torque: '500 Nm',
    drivetrain: 'RWD',
    acceleration: '3.9s',
    fuelEconomy: '8.8 L/100km',
    dimensions: '4379 × 1854 × 1292 mm',
    weight: '1570 kg',
    interior: 'رياضي - جلد أسود',
    wheels: '19".Forge',
    climate: 'تكييف أحادي المنطقة',
    seller: { name: 'عمر الدوسري', rating: 4.8, reviews: 45 },
    features: ['نظام استifferential محدود', 'مكابح Brembo', 'نظام صوت JBL', 'مقاعد رياضية'],
    isAuction: true,
    currentBid: 162000,
    bidCount: 31,
    lastBidTime: '45 ثانية',
    endsAt: Date.now() + 0 * 60 * 60 * 1000 + 0 * 60 * 1000 + 47 * 1000,
  },
  {
    id: '10',
    name: 'Mercedes GLE 450 Coupé',
    nameAr: 'مرسيدس GLE 450 كوبه',
    brand: 'Mercedes',
    brandAr: 'مرسيدس',
    type: 'suv',
    typeAr: 'دفع رباعي',
    year: 2024,
    mileage: 19500,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أبيض ألماني',
    colorEn: 'Polar White',
    location: 'الدمام',
    locationEn: 'Dammam',
    price: 355000,
    startingBid: null,
    image: '/assets/cars/suv_g_class.jpg',
    badge: null,
    engine: '3.0L Inline-6 Turbo',
    power: '381 hp',
    torque: '500 Nm',
    drivetrain: 'AWD',
    acceleration: '5.7s',
    fuelEconomy: '9.5 L/100km',
    dimensions: '4948 × 2010 × 1716 mm',
    weight: '2310 kg',
    interior: 'فاخر - جلد أسود',
    wheels: '22" AMG',
    climate: 'تكييف ثنائي المناطق',
    seller: { name: 'فيصل المالكي', rating: 4.7, reviews: 113 },
    features: ['MBUX', 'نظام صوت Burmester', 'إضاءة محيطية 64 لون', 'مقاعد مساج'],
    isAuction: false,
  },
  {
    id: '11',
    name: 'Audi RS e-tron GT',
    nameAr: 'أودي RS إي-ترون جي تي',
    brand: 'Audi',
    brandAr: 'أودي',
    type: 'sedan',
    typeAr: 'سيدان',
    year: 2024,
    mileage: 6200,
    transmission: 'automatic',
    fuel: 'electric',
    color: 'رمادي كيهرو',
    colorEn: 'Kemora Grey',
    location: 'الرياض',
    locationEn: 'Riyadh',
    price: 520000,
    startingBid: null,
    image: '/assets/cars/sedan_luxury.jpg',
    badge: null,
    engine: 'Electric Dual Motor',
    power: '646 hp',
    torque: '830 Nm',
    drivetrain: 'AWD',
    acceleration: '3.3s',
    fuelEconomy: '0 L/100km',
    dimensions: '4989 × 1936 × 1413 mm',
    weight: '2347 kg',
    interior: 'فاخر - جلد ميكروفايبر',
    wheels: '21" تيتانيوم',
    climate: 'تكييف ثلاثي المناطق',
    seller: { name: 'سلطان العمري', rating: 4.9, reviews: 56 },
    features: ['شحن سريع 270kW', 'نظام صوت Bang & Olufsen', 'Matrix LED', 'نظام تعليق هوائي'],
    isAuction: false,
  },
  {
    id: '12',
    name: 'Chevrolet Corvette C8',
    nameAr: 'شيفرويه كورفيت C8',
    brand: 'Chevrolet',
    brandAr: 'شيفرويه',
    type: 'sports',
    typeAr: 'رياضية',
    year: 2024,
    mileage: 11000,
    transmission: 'automatic',
    fuel: 'gasoline',
    color: 'أصفر آرترا',
    colorEn: 'Accelerate Yellow',
    location: 'جدة',
    locationEn: 'Jeddah',
    price: 275000,
    startingBid: null,
    image: '/assets/cars/sports_orange.jpg',
    badge: null,
    engine: '6.2L V8',
    power: '495 hp',
    torque: '637 Nm',
    drivetrain: 'RWD',
    acceleration: '2.9s',
    fuelEconomy: '11.2 L/100km',
    dimensions: '4630 × 1933 × 1234 mm',
    weight: '1562 kg',
    interior: 'رياضي - GT2',
    wheels: '19"/20" Forged',
    climate: 'تكييف أحادي المنطقة',
    seller: { name: 'ماجد الزهراني', rating: 4.6, reviews: 38 },
    features: ['ن magnetorheological Suspension', 'Performance Data Recorder', 'نظام صوت Bose', 'مقاعد Competizione'],
    isAuction: false,
  },
];

export const brands = [
  { id: 'toyota', name: 'Toyota', nameAr: 'تويوتا', logo: '/assets/logos/toyota.png', count: 42 },
  { id: 'bmw', name: 'BMW', nameAr: 'بي ام دبليو', logo: '/assets/logos/bmw.png', count: 38 },
  { id: 'mercedes', name: 'Mercedes', nameAr: 'مرسيدس', logo: '/assets/logos/mercedes.png', count: 35 },
  { id: 'audi', name: 'Audi', nameAr: 'أودي', logo: '/assets/logos/audi.png', count: 28 },
  { id: 'lexus', name: 'Lexus', nameAr: 'لكزس', logo: '/assets/logos/lexus.png', count: 24 },
  { id: 'ford', name: 'Ford', nameAr: 'فورد', logo: '/assets/logos/ford.png', count: 21 },
  { id: 'hyundai', name: 'Hyundai', nameAr: 'هيونداي', logo: '/assets/logos/hyundai.png', count: 19 },
  { id: 'kia', name: 'Kia', nameAr: 'كيا', logo: '/assets/logos/kia.png', count: 17 },
  { id: 'nissan', name: 'Nissan', nameAr: 'نيسان', logo: '/assets/logos/nissan.png', count: 32 },
  { id: 'gmc', name: 'GMC', nameAr: 'جي إم سي', logo: '/assets/logos/gmc.png', count: 14 },
  { id: 'chevrolet', name: 'Chevrolet', nameAr: 'شيفرويه', logo: '/assets/logos/chevrolet.png', count: 26 },
];

export const vehicleTypes = [
  { id: 'sedan', name: 'سيدان', nameEn: 'Sedan', icon: '🚗', count: 156 },
  { id: 'suv', name: 'دفع رباعي', nameEn: 'SUV', icon: '🚙', count: 234 },
  { id: 'pickup', name: 'بيك أب', nameEn: 'Pickup', icon: '🛻', count: 89 },
  { id: 'sports', name: 'رياضية', nameEn: 'Sports', icon: '🏎️', count: 67 },
  { id: 'coupe', name: 'كوبه', nameEn: 'Coupe', icon: '🚕', count: 45 },
  { id: 'hatchback', name: 'هاتشباك', nameEn: 'Hatchback', icon: '🚘', count: 78 },
  { id: 'van', name: 'فان', nameEn: 'Van/MPV', icon: '🚐', count: 34 },
];

export const tickerItems = [
  { car: 'BMW 740Li', price: '385,000', bids: 12, time: '2:15:00', status: 'Active' },
  { car: 'Mercedes G63 AMG', price: '545,000', bids: 47, time: '0:03:15', status: 'Ending Soon' },
  { car: 'Toyota Land Cruiser', price: '195,000', bids: 24, time: '3:17:42', status: 'Active' },
  { car: 'GR Supra', price: '162,000', bids: 31, time: '0:00:47', status: 'Ending Soon' },
  { car: 'Audi RS e-tron GT', price: '520,000', bids: 8, time: '5:42:00', status: 'Active' },
];

export const auctionCards = [
  cars[2],
  cars[4],
  cars[8],
];
